---
title: "R Notebook"
output: html_notebook
---

```{r}

xy <- replicate(2, rnorm(25))
d <- dist(xy)
st <- simplex_tree(t(combn(25,2))) %>% filtration(d)


st$threshold_index(0)
print(st)
st$threshold_index(10)
print(st)
st$threshold_index(35)
print(st)

st <- simplex_tree() %>% insert(t(combn(10,2)))


st <- st %>% expand(k = 2)


st 


library(simplextree)
st <- simplex_tree(as.list(5:10))
D <- dist(replicate(2, rnorm(st$n_simplices[1])))

density <- floor(0.30*choose(st$n_simplices[1],2))
edges <- sample(st$vertices, size = ifelse(density %% 2, density+1L, density), replace = TRUE)
st %>% insert(matrix(edges, ncol = 2), TRUE)

st$edges
st <- filtration(st, D)
plot(st)
fi <- new(simplextree:::Filtration)


st <- simplex_tree(as.list(5:10)) %>% insert(list(c(5,10), c(5,8), c(8,10), c(5,6), c(7,9), c(7,10)))
st %>% expand(k=2)
dd <- as.matrix(D)[matrix(match(st$edges, st$vertices), ncol = 2)]
st <- filtration(st, dd)

fi$init_tree(st$as_XPtr())
set.seed(1234)
D <- dist(replicate(2, rnorm(fi$n_simplices[1])))
fi$insert(t(combn(fi$n_simplices[1],2))-1L, FALSE)
fi$flag(D)

fi$weights()

structure(fi$simplices, names = seq(0L:(sum(st$n_simplices)-1L)))

fi$current_index
fi$threshold_index(15)
fi$current_index
fi$threshold_index(10)
fi$current_index
fi$threshold_index(15)

fi$remove(fi$simplices[[15]], FALSE)
fi$simplices[[15]]

fi$threshold_index(14)
fi$current_index
fi$threshold_index(13)
fi$current_index
fi$threshold_index(1)
fi$current_index
fi$threshold_index(0)
fi$current_index
fi$threshold_index(1)
fi$current_index
fi$threshold_index(5)
fi$current_index
fi$threshold_index(100)
fi$current_index
fi$threshold_index(0)
x <- do.call(cbind, as.list(k_simplices(st, k = 1)))
simplextree::sub_to_nat(x, 5)
simplextree::sub_to_nat(x, 5)


library(simplextree)
st <- simplextree::simplex_tree()
st %>% insert(1:8)

for (i in 1:100){
  sigma <- sort(sample(1:8, size = runif(1, min = 1, max = 8)))
  if (i %% 2){
    st$insert(sigma, FALSE)
  } else {
    st$remove(sigma, FALSE)
  }
}
st$remove(1:2, FALSE)


st <- simplextree::simplex_tree()
st %>% insert(1:4)
as.list(cofaces(st, 4))
as.list(cofaces(st, c(1,2))) ## repeats 
straverse(simplextree:::parameterize_R(st$as_XPtr(), c(1), "preorder", NULL), identity)

st <- simplextree::simplex_tree() %>% insert(1:4)
ltraverse(simplextree:::parameterize_R(st$as_XPtr(), c(1,4), "coface_roots", NULL), identity)

st <- simplextree::simplex_tree() %>% insert(list(1:3, 2:5))
ltraverse(simplextree:::parameterize_R(st$as_XPtr(), c(3,4), "coface_roots", NULL), identity)
```

```{r}
st <- simplex_tree()
st$insert(1:3, TRUE)
st$remove(1:2, TRUE)
```

