// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/simplextree.h"
#include <Rcpp.h>

using namespace Rcpp;

// profile
NumericVector profile(SEXP st);
RcppExport SEXP _simplextree_profile(SEXP stSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type st(stSEXP);
    rcpp_result_gen = Rcpp::wrap(profile(st));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_union_find_module();
RcppExport SEXP _rcpp_module_boot_simplex_tree_module();

static const R_CallMethodDef CallEntries[] = {
    {"_simplextree_profile", (DL_FUNC) &_simplextree_profile, 1},
    {"_rcpp_module_boot_union_find_module", (DL_FUNC) &_rcpp_module_boot_union_find_module, 0},
    {"_rcpp_module_boot_simplex_tree_module", (DL_FUNC) &_rcpp_module_boot_simplex_tree_module, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_simplextree(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
