# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

n_choose_k <- function(n, k) {
    .Call(`_simplextree_n_choose_k`, n, k)
}

inv_choose_2_R <- function(x) {
    .Call(`_simplextree_inv_choose_2_R`, x)
}

to_subscript_R <- function(numbers, n, k) {
    .Call(`_simplextree_to_subscript_R`, numbers, n, k)
}

to_natural_R <- function(m, n) {
    .Call(`_simplextree_to_natural_R`, m, n)
}

nfold_intersection <- function(x, n) {
    .Call(`_simplextree_nfold_intersection`, x, n)
}

nerve_expand <- function(stx, ids, cover, k, threshold) {
    invisible(.Call(`_simplextree_nerve_expand`, stx, ids, cover, k, threshold))
}

nerve_expand_f <- function(stx, ids, include_f, k) {
    invisible(.Call(`_simplextree_nerve_expand_f`, stx, ids, include_f, k))
}

expand_f_bernoulli <- function(stx, k, p) {
    invisible(.Call(`_simplextree_expand_f_bernoulli`, stx, k, p))
}

profile <- function(st) {
    .Call(`_simplextree_profile`, st)
}

parameterize_R <- function(st, sigma, type, args) {
    .Call(`_simplextree_parameterize_R`, st, sigma, type, args)
}

traverse_R <- function(args, f) {
    invisible(.Call(`_simplextree_traverse_R`, args, f))
}

ltraverse_R <- function(args, f) {
    .Call(`_simplextree_ltraverse_R`, args, f)
}

straverse_R <- function(args, f) {
    .Call(`_simplextree_straverse_R`, args, f)
}

