# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

n_choose_k <- function(n, k) {
    .Call(`_simplextree_n_choose_k`, n, k)
}

inv_choose_2_R <- function(x) {
    .Call(`_simplextree_inv_choose_2_R`, x)
}

to_subscript_R <- function(numbers, n, k) {
    .Call(`_simplextree_to_subscript_R`, numbers, n, k)
}

to_natural_R <- function(m, n) {
    .Call(`_simplextree_to_natural_R`, m, n)
}

nerve_cpp <- function(st, cover, sorted) {
    .Call(`_simplextree_nerve_cpp`, st, cover, sorted)
}

profile <- function(st) {
    .Call(`_simplextree_profile`, st)
}

parameterize_R <- function(st, sigma, type, args) {
    .Call(`_simplextree_parameterize_R`, st, sigma, type, args)
}

traverse_R <- function(args, f) {
    invisible(.Call(`_simplextree_traverse_R`, args, f))
}

ltraverse_R <- function(args, f) {
    .Call(`_simplextree_ltraverse_R`, args, f)
}

straverse_R <- function(args, f) {
    .Call(`_simplextree_straverse_R`, args, f)
}

